### ISSUE TITLE
Admin cannot update or see Status  Tranistion list

### ISSUE THREAD

**Issue by Saylrman64** [speedy32129/time_logger#12]
Hello,

Nie plugin.
It seems to be working OK but in trying to get the Status Transition set up, nothing I do seems to stick. As Admin I select the Time Logger plugin and then select From = "New" to "In Progress" and then click Add Tranition but but it does not show up in the Status Transitions list.
I get no discernable errors in the production.log.

Here is the snippet from the production.log on click Add Transition.
Below it is the Redmine info.
Thanks!
======================================
Started GET "/mpi/settings/plugin/time_logger?&url%5Baction%5D=add_status_transition&url%5Bcontroller%5D=%2Ftime_loggers&complete=%24%28%27status-transition-list%27%29.replace%28request.responseText%29%3B&html%5Bclass%5D=icon+icon-add&with=%27from_id%3D%27+%2B+%24%28%27new-transition-from%27%29.value+%2B+%27%26to_id%3D%27+%2B+%24%28%27new-transition-to%27%29.value" for 192.168.1.22 at 2014-12-30 01:09:12 +0000
Processing by SettingsController#plugin as JS
  Parameters: {"url"=>{"action"=>"add_status_transition", "controller"=>"/time_loggers"}, "complete"=>"$('status-transition-list').replace(request.responseText);", "html"=>{"class"=>"icon icon-add"}, "with"=>"'from_id=' + $('new-transition-from').value + '&to_id=' + $('new-transition-to').value", "id"=>"time_logger"}
  Current user: Admin (id=1)
  Rendered plugins/time_logger/app/views/time_loggers/_status_transition_list.html.erb (2.9ms)
  Rendered plugins/time_logger/app/views/settings/_time_logger.html.erb (3.5ms)
  Rendered settings/plugin.html.erb within layouts/admin (4.4ms)
  Rendered admin/_menu.html.erb (7.9ms)
  Rendered plugins/time_logger/app/views/time_loggers/_embed_menu.html.erb (8.3ms)
  Rendered plugins/time_logger/app/views/time_loggers/_update_menu.html.erb (9.2ms)
  Rendered layouts/base.html.erb (38.3ms)
Completed 200 OK in 55ms (Views: 50.9ms | ActiveRecord: 1.8ms)
======================================

Redmine Info:
Redmine 2.3.0.stable.11718
Default administrator account changed 	True
Attachments directory writable 	True
Plugin assets directory writable 	True
RMagick available (optional) 	True

Environment:
  Redmine version                          2.3.0.stable.11718
  Ruby version                             1.9.3 (x86_64-linux)
  Rails version                            3.2.13
  Environment                              production
  Database adapter                         Mysql2
Redmine plugins:
  redmine_agile                            1.2.0-light
  redmine_better_gantt_chart               0.9.0
  redmine_blocks_layout                    0.0.2
  redmine_dmsf                             1.4.5p1 stable
  redmine_gsc_plantillas                   0.1.0
  redmine_issue_checklist                  2.0.5
  redmine_issue_templates                  0.0.8
  redmine_lightbox                         0.0.1
  redmine_local_avatars                    0.1.1
  redmine_monitoring_controlling           0.1.1
  redmine_questions                        0.0.5
  redmine_reminder                         0.4
  redmine_sidebar_toc_pt                   1.7.0
  redmine_spent_time                       2.6.6
  redmine_tab                              0.4.0
  redmine_zenedit                          0.0.2
  time_logger                              0.5.1
  wiking                                   0.0.4

Production .log snippets:

**Comment by speedy32129** [comment]
This should be fixed.
