### ISSUE TITLE
The problem with the configuration change status

### ISSUE THREAD

**Issue by mrResident** [speedy32129/time_logger#13]
In the plugin settings can not delete transitions between statuses.

**Comment by mrResident** [comment]
Sorry, forgot to write 

 Redmine version            2.6.0.stable
 Ruby version                  2.0.0-p594 (2014-10-27) [x86_64-linux]
 Rails version                  3.2.19

**Comment by speedy32129** [comment]
I am aware of the issue still trying to figure it out.  I'm close.

**Comment by speedy32129** [comment]
You are more than welcome to try the working-redmine-current development branch for testing.  The version should come up as 0.5.2.3.  I'm running on our main production server on 2.2.3 and testing on 3.0.4 with no issues.  Deletes are working perfectly.

**Comment by speedy32129** [comment]
Closing fixed int 0.5.3 public release
