### ISSUE TITLE
Can't start Redmine 2.6 after installing time_logger and run rake redmine:plugin:migrate

### ISSUE THREAD

**Issue by arnoldu** [speedy32129/time_logger#15]
I installed time_logger into $RAILS_ROOT/plugins/time_logger and run rake redmine:plugin:migrate ( in the right rails context!).

Then I restarted my webserver (service nginx restart). Whenever I request a page from redmine, it throws a 500er. The log file reads:

ActionView::Template::Error (Missing partial time_loggers/update_menu with {:locale=>[:de, :en], :formats=>[:html], :handlers=>[:erb, :builder, :rsb]}. Searched in:
  * "/var/www/mqredmine_demo3000/plugins/redmine_dmsf/app/views"
  * "/var/www/mqredmine_demo3000/app/views"

It is not looking in the right folder even it is there. I double checked file owners and permissions. 

What could be wrong? I see a valid directory structure with all files under /var/www/mqredmine_demo3000/plugins/timer_logger

When I delete the time_logger directory redmine works as before.

**Comment by speedy32129** [comment]
I'm not sure and I can't seem to reproduce it.

**Comment by ppoektos** [comment]
You don't need to restart nginx.
You need to restart your ruby web server instead of nginx.

**Comment by speedy32129** [comment]
Thank you ppoektos! I missed that in his description.
