### ISSUE TITLE
Need start time to be logged as a comment after the timer stop.

### ISSUE THREAD

**Issue by VoronyukM** [speedy32129/time_logger#17]
Sometimes you have to provide to a support client a bill with date and time of consultations. Redmine logs only date. So as for me it will be enough to log the start time as a beginning of the comment plugin is generated.
I'm going to do a pull request in near future.

**Comment by speedy32129** [comment]
I have a whole lot better plans than including this.  Soon the time_logger will be completely tracking it's own time in association with the issue time tracking.
