### ISSUE TITLE
Mass-assign error for redmine 3.0.3

### ISSUE THREAD

**Issue by shawndibble** [speedy32129/time_logger#21]
Started GET "/time_loggers/start?issue_id=9910" for 192.168.1.58 at 2015-07-15 12:10:09 -0500
Processing by TimeLoggersController#start as JS
  Parameters: {"issue_id"=>"9910"}
  Current user: sdibble (id=320)
WARNING: Can't mass-assign protected attributes for TimeLogger: issue_id

Missing template, responding with 404
  Rendered common/error.html.erb (0.2ms)
Completed 404 Not Found in 12ms (Views: 0.7ms | ActiveRecord: 0.8ms)

Environment:
  Redmine version                3.0.3.stable.14325
  Ruby version                   2.0.0-p643 (2015-02-25) [x86_64-linux]
  Rails version                  4.2.2
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.8.8
  Mercurial                      2.8.2
  Git                            1.9.1
  Filesystem                     

Using:   time_logger                    0.5.2

**Comment by rastydnb** [comment]
I have the same issue


Started GET "/time_loggers/start?issue_id=1" for 80.25.144.5 at 2015-07-22 10:45:21 +0200
Processing by TimeLoggersController#start as JS
  Parameters: {"issue_id"=>"1"}
  Current user: lramos (id=3)
WARNING: Can't mass-assign protected attributes for TimeLogger: issue_id

Environment:
Redmine version 3.0.3.stable.14325
Ruby version 2.1.5p273
Rails version 4.2.1
Environment production
Database adapter Mysql2
SCM:
Git 2.1.4
Filesystem

**Comment by rastydnb** [comment]
in app/models/time_logger.rb i added this line "attr_accessible :issue_id" after "has_one :issue" and worked for me, if speedy32129 like i can make a  pull request

**Comment by speedy32129** [comment]
I'm trying to reproduce the issue.  Going to a fresh install and your version.  Can you please tell me what you were doing to get the error that might help.  Was it just starting the time_logger?  You are most than welcome to do a pull request and make the the change.  Once I'm able to reproduce the problem and check your fix and test it on a few other version I'll pull in into the repository.  I love giving credit where credit is due!

**Comment by shawndibble** [comment]
Steps: open an issue. Click start. Nothing happens. Check logs. see error.

Also, thank you rastydnb, your solution worked for me.

**Comment by speedy32129** [comment]
I believe this is fixed in 0.5.3
