### ISSUE TITLE
Bug in the new version

### ISSUE THREAD

**Issue by tolstenko** [speedy32129/time_logger#22]
Please, the new version isnt working for redmine 3.0.4. Should I update to 3.2? 

In the redmine wiki says:
"Compatible with Redmine 3.2.x, 3.1.x, 3.0.x, 2.6.x, 2.5.x, 2.4.x, 2.3.x, 2.2.x, 2.1.x, 2.0.x. Several fixes and now compatible with Redmine 3.2"

But whis version doesnt work yet in the redmine 3.0.4 yet. 

I downloaded the 0.5.2 from your git and installed as any other plugin.
I made a video to repoduce the bug:

https://mega.nz/#!BJcCAKYB!RH7d6Kl3AE8TWJl8lVvHrsMLQoAcvcehC-GkXGRYZm4

Thanks for your effort

**Comment by janekska** [comment]
I have the same problem.

Here are my system:
Environment:
  Redmine version                3.0.3.stable
  Ruby version                   1.9.3-p551 (2014-11-13) [x86_64-linux]
  Rails version                  4.2.1
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.6.17
  Mercurial                      2.0.2
  Git                            1.7.9.5
  Filesystem                     
Redmine plugins:
  accept                         0.0.1
  event_notifications            3.0.0
  redmine_dashboard              2.5.0
  redmine_mail_reminder          3.0.0.0001
  redmine_theme_changer          0.2.0
  time_logger                    0.5.2

**Comment by speedy32129** [comment]
tolstenko do you have any other plugins installed?

**Comment by yahorosh** [comment]
Hello. 

Can't install to 3.0.4

Try to install manual (copy files run sql)

```
Processing by TimeLoggersController#suspend as JS
  Current user: asd (id=3)
Completed 500 Internal Server Error in 8ms (ActiveRecord: 0.7ms)

TypeError (nil is not a symbol nor a string):
  app/controllers/time_loggers_controller.rb:58:in `suspend'

```

or 

```
Processing by TimeLoggersController#index as HTML
  Current user: horoshev (id=3)
  Rendered time_loggers/index.html.erb within layouts/base (2.8ms)
Completed 500 Internal Server Error in 8ms (ActiveRecord: 0.5ms)

ActionView::Template::Error (undefined local variable or method `help' for #<TimeLogger:0x007f74eb384f48>):
    21:                     <tbody>
    22:                         <% for time_logger in @user_time_loggers %>
    23:                             <tr id="user-timetracker<%= time_logger.id %>" class="<%= cycle('odd', 'even') %>">
    24:                                 <% if time_logger.zombie? %>
    25:                                     <% has_zombie = true %>
    26:                                     <td class="zombie icon icon-warning"></td>
    27:                                 <% else %>
  app/models/time_logger.rb:38:in `zombie?'
  app/views/time_loggers/index.html.erb:24:in `block in _app_views_time_loggers_index_html_erb___3171713390009182212_38541060'
  app/views/time_loggers/index.html.erb:22:in `_app_views_time_loggers_index_html_erb___3171713390009182212_38541060'
```

**Comment by speedy32129** [comment]
The time_logger you installed is a development copy.  You can use the use the current tagged version of 0.5.2 or the master which should be the same.  Also I did notice that error when working on it and if you wanted to try the current development version that can be found under working-redmine-current which happens to be version 0.5.2.3 which I'm still testing but it should work.  This version had some pretty major changes however the configurations status transitions are working.

**Comment by speedy32129** [comment]
tolstenko ->  I re-watched your video.  in version 0.5.2 you must click apply after adding all your status transitions.  The latest development version I'm getting ready to remove the apply button.  I'm also adding better instructions soon. 

Also re-watching the video I saw the other plugins all but one I'm familiar with and has had no symptoms of trouble with the time_logger which also has been fix in the latest development version.

Please as far as the time_logger not being able to start I think that's what you were trying to show me at the beginning of the video.  I saw you created a task. What I didn't see was if you had rights to log time to that project under the project settings.  I'd be more than happy to check your site for you just pm me the info.
