### ISSUE TITLE
List of time trackers always empty

### ISSUE THREAD

**Issue by mwalimu82** [speedy32129/time_logger#23]
I love this plugin but there is one little problem I have:
Logging my time works perfect and if I click on "Overall spent time" I see the entries in the list.
But... if I click on that list symbol on the top right corner next to "my account" I always get:

Time trackers
Your time tracker
No time tracker
Other user's time trackers
No time tracker

I expected here a list of all time entries. Do I misunderstand it or is something going wrong?
Many thanks
Marko

**Comment by speedy32129** [comment]
The time trackers list is only for active time loggers otherwise you have to use the builtin time spent http://<url>/time_entries.  I am planning on adding only the current day to the existing list under the other user's time trackers.
