### ISSUE TITLE
Spent time in Field permissions

### ISSUE THREAD

**Issue by janmashat** [speedy32129/time_logger#25]
Firstly, great work on this plugin...I can't believe its not included in the core.

Secondly, is there any chance you're planning to add Spent time to the Field permissions page so it can be set as a required field for certain role/tracker combinations?
https://www.redmine.org/attachments/download/7941/workflow_permissions.png

**Comment by speedy32129** [comment]
That's a pretty good question however, if I'm right, spent time is in the core of Redmine and not a part of my plugin.

![image](https://cloud.githubusercontent.com/assets/937458/9943458/5d7a22e0-5d4f-11e5-9af0-fa115b1397cd.png)
