### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by bantu** [speedy32129/time_logger#26]
Hello

This projects looks exactly what I am looking for. I'd appreciate if you could put up a few screenshots of the functionality to make sure.

Thanks

Cheers

**Comment by cdp1337** [comment]
![rm-screenshot-1](https://cloud.githubusercontent.com/assets/737865/10434480/c70ecf48-70e7-11e5-8288-181ee9ef5a5d.png)
![rm-screenshot-2](https://cloud.githubusercontent.com/assets/737865/10434481/cac8ef2e-70e7-11e5-8e29-6a017257b66b.png)

Pretty simple of a module, adds the little timer in the corner.

**Comment by bantu** [comment]
Thanks a lot.

**Comment by speedy32129** [comment]
here's a shot of current active time trackers.
![image](https://cloud.githubusercontent.com/assets/937458/10436584/4b43cc8e-70f5-11e5-90d8-357f25271ad5.png)

**Comment by cdp1337** [comment]
OH yeah, I think I moved my time tracker box outside of the top UI to make it stand out a little more.

**Comment by speedy32129** [comment]
There is a note that require a little uncommenting and commenting in the time_logger.css.  I'm hoping to make it just an administrative and/or user option.
