### ISSUE TITLE
Only show one issue

### ISSUE THREAD

**Issue by drdelportillo** [speedy32129/time_logger#27]
Hello first excellent plugin but I use the version 3.0.4 and list requests only one single request comes running if another think the change of state to run simultaneously gives me the option to start or whether anything more can measure one- time request , not an error or if the plug is so

can you help me

Thank you

I apologize for my English I speak Spanish

**Comment by speedy32129** [comment]
I hope I understand what your saying.  It sounds like you prefer to have more than one timer  tracker/logger running per individual.  Is that correct?  If so, I'm sorry,mine doesn't currently allow multiple trackers/loggers but most likely to become an administrative option if I can get a java-script/ajax person to help with a slide in panel for the loggers.  However there are a couple of other plugins that currently do allow multiple tracker/loggers (i.e hicknhack-software is one https://github.com/hicknhack-software/redmine_time_tracker) .

**Comment by drdelportillo** [comment]
thanks
