### ISSUE TITLE
Per issue timer don't start

### ISSUE THREAD

**Issue by reida** [speedy32129/time_logger#32]
Hi. When I start timer per some issue, I can't start new timer for another. Pause wont help. Only stop timer (but it close my issue) allow me to start new one.

Environment:
  Redmine version                3.2.1.stable
  Ruby version                   2.1.8-p440 (2015-12-16) [i386-freebsd10]
  Rails version                  4.2.5.2
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.9.3
  Git                            2.7.4
  Filesystem                     
Redmine plugins:
  a_common_libs                  2.1.8
  progressive_projects_list      3.0.1
  redmine_ckeditor               1.1.3
  redmine_codebutton             0.1.0
  redmine_dmsf                   1.5.6
  redmine_highlightjs            1.0.3
  redmine_lightbox2              0.2.5
  redmine_revision_branches      0.3.1
  redmine_tweaks                 0.5.7
  time_logger                    0.5.3
  usability                      2.1.2

**Comment by speedy32129** [comment]
The current version only supports 1 active time logger. There are a couple of other plugins that allow multiple times loggers. This is something I may support as an option but my intended use is for one.

**Comment by reida** [comment]
Thanks for the answer
