### ISSUE TITLE
Internal error 500 start redmine

### ISSUE THREAD

**Issue by noobchamp** [speedy32129/time_logger#33]
hi friend. In my redmine 3.0.4 and your last version plugin (0.5.3). can you see details production.log

Rendered welcome/index.html.erb within layouts/base (88.1ms)
Missing template, responding with 404
  Rendered common/error.html.erb within layouts/base (1.2ms)
Completed 500 Internal Server Error in 560ms (ActiveRecord: 9.7ms)

ActionView::Template::Error (Missing partial time_loggers/_update_menu with {:locale=>[:es, :en], :formats=>[:html], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby, :haml, :rsb]}. Searched in:
- "/opt/redmine/redmine-3.0.4/plugins/redmine_work_time/app/views"
- "/opt/redmine/redmine-3.0.4/plugins/redmine_wktime/app/views"
- "/opt/redmine/redmine-3.0.4/plugins/redmine_git_hosting/app/views"
- "/opt/redmine/redmine-3.0.4/plugins/redmine_bootstrap_kit/app/views"
- "/opt/redmine/redmine-3.0.4/app/views"
  ):
  72:   <div class="bgl"><div class="bgr">
  73:     Powered by <%= link_to Redmine::Info.app_name, Redmine::Info.url %> &copy; 2006-2015 Jean-Philippe Lang
  74:   </div></div>
  75: </div>
  76: </div>
  77: </div>
  78: <%= call_hook :view_layouts_base_body_bottom %>
  lib/redmine/hook.rb:119:in `block (2 levels) in render_on'
  lib/redmine/hook.rb:117:in`map'
  lib/redmine/hook.rb:117:in `block in render_on'
  lib/redmine/hook.rb:61:in`block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in`block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in`call_hook'
  lib/redmine/hook.rb:167:in `call_hook'
  app/views/layouts/base.html.erb:75:in`_app_views_layouts_base_html_erb__4416577588912088716_67777900'
  app/controllers/application_controller.rb:469:in `block (2 levels) in render_error'
  app/controllers/application_controller.rb:467:in`render_error'
  app/controllers/application_controller.rb:455:in `render_404'
  app/controllers/application_controller.rb:479:in`missing_template'

Do you can help me please? Thanks!

**Comment by heidricha** [comment]
same for me
redmine 3.2

**Comment by speedy32129** [comment]
Are these clean installs?  Any other plugins?  I have seen a couple of these and I'm now getting suspicious this may be something I need to dig into but mostly I don't see this error on clean installs.  I have seen it have issues with a few other plugins. Removing the other plugins one at a time should help trying to resolve the issue as we should be able to figure out if the problem is my plugin or theirs.  Once you find the other plugin it's having an issue with and it's been removed install my plugin and you shouldn't get the error.  Then give me the name and I'll figure out what's wrong.  If you can't do all that all I suggest is give then the output from below.

If you go to the Administration -> Information page and copy the from  environment down and paste the info here.

**Comment by CrackAjax** [comment]
I am getting the same issue.  I am on a clean install and only have the plugins that came with the original install.  My log says:

Started GET "/redmine/projects" for 192.168.1.55 at 2016-06-21 11:27:10 -0600
Processing by ProjectsController#index as HTML
  Current user: admin (id=1)
  Rendered projects/index.html.erb within layouts/base (8.5ms)
Missing template, responding with 404
  Rendered common/error.html.erb within layouts/base (0.1ms)
Completed 500 Internal Server Error in 26.0ms

ActionView::Template::Error (Missing partial time_loggers/update_menu with {:locale=>[:en], :formats=>[:html], :handlers=>[:erb, :builder, :rsb]}. Searched in:
  * "/usr/share/redmine/app/views"
):
    72:   <div class="bgl"><div class="bgr">
    73:     Powered by <%= link_to Redmine::Info.app_name, Redmine::Info.url %> &copy; 2006-2013 Jean-Philippe Lang
    74:   </div></div>
    75: </div>
    76: </div>
    77: </div>
    78: <%= call_hook :view_layouts_base_body_bottom %>
  lib/redmine/hook.rb:111:in `block in render_on'
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:158:in `call_hook'
  app/views/layouts/base.html.erb:75:in `_app_views_layouts_base_html_erb___1619552058601944653_39171940'
  app/controllers/application_controller.rb:429:in `block (2 levels) in render_error'
  app/controllers/application_controller.rb:427:in `render_error'
  app/controllers/application_controller.rb:415:in `render_404'
  app/controllers/application_controller.rb:439:in `missing_template'

and the Information page says:

Information
Redmine 2.4.2.stable

Default administrator account changed	True
Attachments directory writable	True
Plugin assets directory writable	True
RMagick available (optional)	Exclamation
ImageMagick convert available (optional)	Exclamation

Environment:
  Redmine version                2.4.2.stable
  Ruby version                   1.9.3-p484 (2013-11-22) [x86_64-linux]
  Rails version                  3.2.16
  Environment                    production
  Database adapter               MySQL
SCM:
  Subversion                     1.8.8
  Mercurial                      2.8.2
  Cvs                            1.12.13
  Git                            1.9.1
  Filesystem                     
Redmine plugins:
  no plugin installed

Looking forward to using your plugin once I can get it to work.

**Comment by speedy32129** [comment]
The plugin works.  It doesn't look like you did the rake db:migrate_plugins RAILS_ENV=production,  make sure the directory is time_logger and restart apache or whatever web server you are using.

**Comment by CrackAjax** [comment]
I reinstalled the plugin in my redmine plugin directory and did the rake:


On Wed, Jun 22, 2016 at 8:58 AM, speedy32129 <notifications@github.com>
wrote:

> The plugin works. It doesn't look like you did the rake db:migrate_plugins
> RAILS_ENV=production, make sure the directory is time_logger and restart
> apache or whatever web server you are using.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/speedy32129/time_logger/issues/33#issuecomment-227771440>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AHwK4CH-r4y-Kw1UONle6K374tf8sffjks5qOU2pgaJpZM4IKcKY>
> .
>



-- 
Thanks,
Donald K. Seigler

Its not who you are, but what you do.  Daniel Coyle

**Comment by CrackAjax** [comment]
I reinstalled the plugin in my redmine plugins directory and did the rake:

crack-ajax@crack-ajax-serves-hp:/usr/share/redmine/lib/plugins$ sudo rake
redmine:plugins:migrate RAILS_ENV=production
(in /usr/share/redmine)
Migrating time_logger (Time Logger)...


However, I am still getting the 500 error.

On Wed, Jun 22, 2016 at 8:58 AM, speedy32129 <notifications@github.com>
wrote:

> The plugin works. It doesn't look like you did the rake db:migrate_plugins
> RAILS_ENV=production, make sure the directory is time_logger and restart
> apache or whatever web server you are using.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/speedy32129/time_logger/issues/33#issuecomment-227771440>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AHwK4CH-r4y-Kw1UONle6K374tf8sffjks5qOU2pgaJpZM4IKcKY>
> .
>



-- 
Thanks,
Donald K. Seigler

Its not who you are, but what you do.  Daniel Coyle

**Comment by CrackAjax** [comment]
Here is my production.log report on the 500:

Started GET "/redmine/roles" for 192.168.1.55 at 2016-06-22 09:41:32 -0600
Processing by RolesController#index as HTML
  Current user: Crack-Ajax (id=1)
  Rendered roles/index.html.erb within layouts/admin (7.0ms)
  Rendered admin/_menu.html.erb (3.9ms)
  Rendered layouts/base.html.erb (7.6ms)
Missing template, responding with 404
  Rendered common/error.html.erb within layouts/base (0.1ms)
Completed 500 Internal Server Error in 27.1ms

ActionView::Template::Error (Missing partial time_loggers/update_menu with
{:locale=>[:en], :formats=>[:html], :handlers=>[:erb, :builder, :rsb]}.
Searched in:
  * "/usr/share/redmine/app/views"
):
    72:   <div class="bgl"><div class="bgr">
    73:     Powered by <%= link_to Redmine::Info.app_name,
Redmine::Info.url %> &copy; 2006-2013 Jean-Philippe Lang
    74:   </div></div>
    75: </div>
    76: </div>
    77: </div>
    78: <%= call_hook :view_layouts_base_body_bottom %>
  lib/redmine/hook.rb:111:in `block in render_on'
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:158:in `call_hook'
  app/views/layouts/base.html.erb:75:in
`_app_views_layouts_base_html_erb__4588625996014710231_37265700'
  app/controllers/application_controller.rb:429:in `block (2 levels) in
render_error'
  app/controllers/application_controller.rb:427:in `render_error'
  app/controllers/application_controller.rb:415:in `render_404'
  app/controllers/application_controller.rb:439:in `missing_template'


On Wed, Jun 22, 2016 at 9:41 AM, Donald Seigler <dkseigler@gmail.com> wrote:

> I reinstalled the plugin in my redmine plugins directory and did the rake:
>
> crack-ajax@crack-ajax-serves-hp:/usr/share/redmine/lib/plugins$ sudo rake
> redmine:plugins:migrate RAILS_ENV=production
> (in /usr/share/redmine)
> Migrating time_logger (Time Logger)...
>
>
> However, I am still getting the 500 error.
>
> On Wed, Jun 22, 2016 at 8:58 AM, speedy32129 <notifications@github.com>
> wrote:
>
>> The plugin works. It doesn't look like you did the rake
>> db:migrate_plugins RAILS_ENV=production, make sure the directory is
>> time_logger and restart apache or whatever web server you are using.
>>
>> —
>> You are receiving this because you commented.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/speedy32129/time_logger/issues/33#issuecomment-227771440>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe/AHwK4CH-r4y-Kw1UONle6K374tf8sffjks5qOU2pgaJpZM4IKcKY>
>> .
>>
>
>
>
> --
> Thanks,
> Donald K. Seigler
>
> Its not who you are, but what you do.  Daniel Coyle
>



-- 
Thanks,
Donald K. Seigler

Its not who you are, but what you do.  Daniel Coyle

**Comment by speedy32129** [comment]
Can you paste the all info from the -> administration -> information page again?

**Comment by CrackAjax** [comment]
*Redmine 2.4.2.stable*
Default administrator account changed [image: True]
Attachments directory writable [image: True]
Plugin assets directory writable [image: True]
RMagick available (optional) [image: Exclamation]
ImageMagick convert available (optional) [image: Exclamation]

Environment:
  Redmine version                2.4.2.stable
  Ruby version                   1.9.3-p484 (2013-11-22) [x86_64-linux]
  Rails version                  3.2.16
  Environment                    production
  Database adapter               MySQL
SCM:
  Subversion                     1.8.8
  Mercurial                      2.8.2
  Cvs                            1.12.13
  Git                            1.9.1
  Filesystem
Redmine plugins:
  no plugin installed


On Wed, Jun 22, 2016 at 10:37 AM, speedy32129 <notifications@github.com>
wrote:

> Can you paste the all info from the -> administration -> information page
> again?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/speedy32129/time_logger/issues/33#issuecomment-227802215>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AHwK4MT2D8ogWcw8ntz4DCUm_xLjSdlaks5qOWS4gaJpZM4IKcKY>
> .
>



-- 
Thanks,
Donald K. Seigler

Its not who you are, but what you do.  Daniel Coyle

**Comment by speedy32129** [comment]
Obviously there is something wrong here.

Redmine plugins:
  no plugin installed

What version of the time_logger are you trying to use?

**Comment by CrackAjax** [comment]
I am pulling from the git repository
https://github.com/speedy32129/time_logger.git.  Because of the 500 error,
I deleted it back out so I could access my Redmine.  When I have it
installed I cannot access anything.

On Wed, Jun 22, 2016 at 12:23 PM, speedy32129 <notifications@github.com>
wrote:

> Obviously there is something wrong here.
>
> Redmine plugins:
> no plugin installed
>
> What version of the time_logger are you trying to use?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/speedy32129/time_logger/issues/33#issuecomment-227833528>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AHwK4BcFTDcmzNIT7sFPpiCspYJrrP98ks5qOX2pgaJpZM4IKcKY>
> .
>



-- 
Thanks,
Donald K. Seigler

Its not who you are, but what you do.  Daniel Coyle

**Comment by speedy32129** [comment]
I'm seeing an issue can you try git clone --branch 0.5.3  https://github.com/speedy32129/time_logger.git

**Comment by CrackAjax** [comment]
I installed the branch 0.5.3 and am continuing to get the 500 error.

On Wed, Jun 22, 2016 at 1:14 PM, speedy32129 <notifications@github.com>
wrote:

> I'm seeing an issue can you try git clone --branch 0.5.3
> https://github.com/speedy32129/time_logger.git
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/speedy32129/time_logger/issues/33#issuecomment-227847861>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AHwK4LnFVDw9nZmdSbcdd4ML0xKc8e-Zks5qOYmUgaJpZM4IKcKY>
> .
>



-- 
Thanks,
Donald K. Seigler

Its not who you are, but what you do.  Daniel Coyle

**Comment by speedy32129** [comment]
So far I've had no issue.  I created a VM and installed it on 2.4.2 stable and other than the SCM updates you appear to have is the ruby version.  I'm on 1.9.3-p194.  I'm working on trying to upgrade it to 1.9.3-p484.  The other thing is the database adapter is Mysql2 on my vm. I'll let you know how that turns out.

**Comment by davidbenucci** [comment]
Hi all! I have the same problem. On Redmine index page I got 500 internal error. I have redmine 3.2.3-2 and 0.54 version of your plugin. This is my log:

Started GET "/redmine/" for 2.228.69.230 at 2017-02-03 11:26:53 +0100
Processing by WelcomeController#index as HTML
  Current user: anonymous
  Rendered welcome/index.html.erb within layouts/base (101.5ms)
Missing template, responding with 404
  Rendered common/error.html.erb within layouts/base (1.3ms)
Completed 500 Internal Server Error in 847ms (ActiveRecord: 26.3ms)

ActionView::Template::Error (Missing partial time_loggers/_update_menu with {:l$
  * "/usr/share/redmine/app/views"
):
    115:   <div class="bgl"><div class="bgr">
    116:     Powered by <%= link_to Redmine::Info.app_name, Redmine::Info.url %$
    117:   </div></div>
    118: </div>
    119: </div>
    120: </div>
    121: <%= call_hook :view_layouts_base_body_bottom %>
  lib/redmine/hook/view_listener.rb:59:in `block (2 levels) in render_on'
  lib/redmine/hook/view_listener.rb:57:in `map'
  lib/redmine/hook/view_listener.rb:57:in `block in render_on'
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:96:in `call_hook'
  app/views/layouts/base.html.erb:118:in `_app_views_layouts_base_html_erb__435$
  app/controllers/application_controller.rb:470:in `block (2 levels) in render_$
  app/controllers/application_controller.rb:468:in `render_error'
  app/controllers/application_controller.rb:456:in `render_404'
  app/controllers/application_controller.rb:480:in `missing_template'

```

**Comment by dsdebastiani** [comment]
The pluggin don't work with some themes. The default theme works fine.
