### ISSUE TITLE
TimeLogger for not admin's user

### ISSUE THREAD

**Issue by Minotti** [speedy32129/time_logger#45]
Hello, I would like to ask for help. What it takes for a user other than admin can activate timelogger? For the admin's timelogger appears, for others not. Because?

**Comment by jmlagace** [comment]
Hello Minotti, 

If you mean "Activate" by starting the timelogger onto a task a non-admin user simply needs to open an issue and the time logger will be visible at the top of the page.  Right clicking an issue will also allow starting the timelogger for that task. 

From the moment you have running timelogger you can view your data. 

If you mean viewing other people's timelogger check into the Project permissions under the role of your non-admin user.

**Comment by speedy32129** [comment]
non-issue
