### ISSUE TITLE
Transition status

### ISSUE THREAD

**Issue by tuliobmachado** [speedy32129/time_logger#48]
Hello, is it necessary to perform some configuration so as to change a state, the timer starts counting automatically? I registered a state but changing it to the new state the team is not counting ... What permissions do I need to be able to use this automatic function? 
My version and plugins used:
Environment:
  Redmine version                3.3.1.stable
  Ruby version                   2.2.6-p396 (2016-11-15) [x86_64-linux]
  Rails version                  4.2.7.1
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.6.11
  Filesystem                     
Redmine plugins:
  redmine_agile                  1.4.2
  time_logger                    0.5.4

**Comment by speedy32129** [comment]
You mean to change the status from new to in progress or something like that?  If so the user needs to have permissions to change status.

**Comment by tuliobmachado** [comment]
I understand, I am using an Agile CRM plugin my user is unique and administrator .. Is this the problem?

**Comment by tuliobmachado** [comment]
Good night, my user is part of the role "developer" where it has all permissions checked, however it was seen that in the permissions only have 2 options related to the timer logger that are:
"View other users' time trackers" and "Delete time trackers from other users" is correct? Or should any more permission appear?

**Comment by mrResident** [comment]
> You mean to change the status from new to in progress or something like that?

That's right, there was a mean change from a new status to the next. I originally incorrectly described the problem. The problem lies in the plugin settings, I'am can not add a transition from one status to another. I choose my desired transition, click on "Add transition" and nothing happens. The selected transition is not added to the list.

**Comment by speedy32129** [comment]
this issue was fixed in 0.5.4
