### ISSUE TITLE
Status transition ERROR

### ISSUE THREAD

**Issue by n158** [speedy32129/time_logger#52]
When start time tracking, status changes from "In Progress" to "Resolved". Time Logger 0.5.4, Redmine 3.3.0.

**Comment by speedy32129** [comment]
Can you go to Administration -> plugins -> time logger -> configure and send a screen shot? If you can. This should not happen unless that's how the administrator has set things up.

**Comment by n158** [comment]
https://ibb.co/bUBDR5
The problem is that transition from status "In progress" to "Resolved" occurs at the start of time logging, which is not acceptable. What can you suggest in this case?

**Comment by speedy32129** [comment]
Oh I wouldn't put a transition here if that was the case as transition happens on the pickup of a task.   Tasks can't always be completed in a single shot or log entry in other words it might take days for a task to be completed and you may get interrupted etc.  This time logger is to really only be used when you actually working on an item.

**Comment by n158** [comment]
Ok. So this problem is closed now.

**Comment by speedy32129** [comment]
Of coarse you can change the status on the complete of the log entry.  I hope that makes sense.
