### ISSUE TITLE
this dose not work on version 3.4.x

### ISSUE THREAD

**Issue by Abiab01** [speedy32129/time_logger#53]
hi team 
we are trying to install it on version 3.4.x bt time logger does not work properly

**Comment by DarianAnjuhal** [comment]
@speedy32129 Same question here, do you guys know a smilar plugin?

**Comment by somnibusse** [comment]
The fork https://github.com/zloynemec/time_logger runs under Redmine 3.4.3.stable.

**Comment by speedy32129** [comment]
Current version is working to version 4.0.3
