### ISSUE TITLE
Redmine 4.x compatibility

### ISSUE THREAD

**Issue by JanMalte** [speedy32129/time_logger#63]
Is this plugin compatible with Redmine 4.0? Or do you plan to make it compatible?

**Comment by petrposvic** [comment]
I use this plugin on 4.0.4 and no problem.

**Comment by rootninja** [comment]
confirmed with the following config: (great plugin, thank you Jim!) 
Environment:
  Redmine version                4.0.5.stable
  Ruby version                   2.6.3-p62 (2019-04-16) [x86_64-linux]
  Rails version                  5.2.3
  Environment                    production
  Database adapter               PostgreSQL
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Git                            1.8.3.1
  Filesystem                     
Redmine plugins:
  time_logger                    0.5.4
